// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Gatsby from "gatsby";

var Link = /* module */[];

function Excerpt$SpecialLink(Props) {
  var isExternal = Props.isExternal;
  var _to = Props.to;
  var children = Props.children;
  if (isExternal) {
    return React.createElement("a", {
                href: _to,
                rel: "external"
              }, children);
  } else {
    return React.createElement(Gatsby.Link, {
                to: _to,
                children: children
              });
  }
}

var SpecialLink = /* module */[/* make */Excerpt$SpecialLink];

export {
  Link ,
  SpecialLink ,
  
}
/* react Not a pure module */
